[client]
showSidebarNavigation = false

[theme]
primaryColor="#9ad8e1"
backgroundColor="#000890"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[chainlink]
user="RGRIGGS0927"
password = "Cyaamstr927!"
account = "OEZIERR-CNB82593"
warehouse = "CHAINLINKANALYTICS_WH"
database = "TENANTUSERDB"
schema = "CHAINLINK_SCH"

[mailjet]
API_KEY = "e11ddbd337f184e6d01ae788b7e9a49f"
SECRET_KEY = "f7d7b721f6dd80d504923723f5634c63"

[cookie_key]
cookie_secret_key = "mIrTESTvHF6jJijhPC8d4prUpexfXQT__h_2SaKMACI"

